[package]
name = "rusty-horse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
csv = "1.3.0"
dialoguer = { version = "0.11.0", default-features = false, features = ["fuzzy-select"] }
flate2 = "1.0.28"
futures = "0.3.30"
indicatif = { version = "0.17.8" }
reqwest = { version = "0.11.27", default-features = false, features = ["rustls-tls", "stream"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
